@ECHO OFF

FOR /D %%D IN (*.*) DO CALL :RUN_ALL_SUB %%D

EXIT /B
GOTO :EOF

:RUN_ALL_SUB
SET SUB_DIR=%~dp0%1
IF NOT EXIST %SUB_DIR%\RUN_ALL.BAT GOTO :EOF
PUSHD %SUB_DIR%
CALL %SUB_DIR%\make_all_bat.bat
POPD
GOTO :EOF
