@ECHO OFF

FOR /D %%D IN (*.*) DO CALL :RUN_ALL_SUB %%D

EXIT /B
GOTO :EOF

:RUN_ALL_SUB
SET SUB_DIR=%~dp0%1
IF NOT EXIST %SUB_DIR%\run_all.bat GOTO :EOF
PUSHD %SUB_DIR%
CALL %SUB_DIR%\run_all.bat
POPD
GOTO :EOF
